### PR TITLE
Add extra constants for tcpdf config

### PR DESCRIPTION
**Pull request by it-can**
I added all the constants defined in the tcpdf_config.php file of TCPDF.

### CODE REVIEW

**Comment by elibyy** [comment]
this is very nice, thank you, i will push it later, cause of the other branches needs to get the update and not only master

**Comment by it-can** [comment]
hey @elibyy I see you created 5.2.3 release, but I am not getting this from composer (it still installs 5.2.2)

**Comment by elibyy** [comment]
it's odd as i can see it on [packagist](https://packagist.org/packages/elibyy/tcpdf-laravel#5.2.3), could you share your **composer.json**

**Comment by it-can** [comment]
`"elibyy/tcpdf-laravel": "5.2.*"`

**Comment by elibyy** [comment]
i can't seem to see the problem in your side, i just ran it in my machine and it's installing `5.2.3` are you running `composer update`? also try [clearing the cache](https://hakre.wordpress.com/2014/05/27/composer-clear-cache/)

**Comment by it-can** [comment]
doesn't fix it..., maybe do a force update on packagist?

**Comment by elibyy** [comment]
i'm not that familiar with composer so, I think you should ask your question in composer repository or stackoverflow, I'm sorry i can't help further more

**Comment by it-can** [comment]
When you login into packagist, you can do a force update on your repo's, this should fix the problem I think

**Comment by elibyy** [comment]
performed forced-update

**Comment by it-can** [comment]
still doesnt work... weird...

you get the correct version in composer?

**Comment by elibyy** [comment]
I've created empty project, added the line you have specified in `required` in `composer.json` and ran `composer install` and i got 5.2.3

**Comment by it-can** [comment]
When I do that, I get 5.2.2

**Comment by elibyy** [comment]
you should do `composer update`
also on what environment are you running? windows/linux

**Comment by it-can** [comment]
Mac and running composer update... On new project also getting 5.2.2

**Comment by it-can** [comment]
on an empty project (no laravel) I get 5.2.3, but in a laravel project 5.2.2

**Comment by elibyy** [comment]
OK i was too quick on release creation i accidentally created 5.2.3 on 5.0 branch

**Comment by it-can** [comment]
aaah ok...

**Comment by it-can** [comment]
Did you fix it?

**Comment by elibyy** [comment]
yeah, you should test and let me know

**Comment by it-can** [comment]
Ok will try tomorrow thanks!

**Comment by it-can** [comment]
Still doesn't work...

**Comment by elibyy** [comment]
ok, ran the following `composer create-project --prefer-dist laravel/laravel blog` and then added the line to composer.json and then `composer update` 

`- Installing elibyy/tcpdf-laravel (5.2.3)`

maybe you should clear cache and stuff like that

**Comment by it-can** [comment]
Yes it now finally works... Removed the vendor directory of composer... weird...

Thanks for the help!

**Pull request closed without merging**
